<?php

return [
    'activity_shifts' => [1 => 'Morning', 2 => 'Afternoon',3 => 'Evening', 4 => 'Night'],
	'geofencing_status' => [0 => 'Inactive', 1 => 'Active'],
	'activity_types' => [0 => 'None', 1 => 'Input', 2 => 'Radio', 3 => 'Checkbox', 4 => 'Select', 5 => 'Multiselect', 6 => 'Time', 7 => 'TextArea'],
    // 'log_times' => [1 => '8:00 AM - 11:59 AM', 2 => '2:00 PM - 5:59 PM', 3 => '8:00 PM - 10:59 PM'],
	'log_times' => [1 => '5:00 - 11:59', 2 => '12:00 - 16:59', 3 => '17:00 - 23:59',4 => '00:01 - 04:59'],
    'medicine_type' => [1 => 'Pill', 2 => 'Liquid', 3 => 'Cream', 4 => 'Injection', 5 => 'Other'],
    'dose_type' => ['mg' => 'mg', 'mcg' => 'mcg', 'ml' => 'ml', 'µL' => 'µL', 'other' => 'Other'],
    'medicine_time' => [1 => 'Morning', 2 => 'Afternoon',3 => 'Evening', 4=>'Night', 6 => 'As Needed', 5 => 'Other'],
    'medicine_time_other' => [1 => 'Breakfast', 2 => 'Lunch', 3=>'Dinner', 4 => 'Supper'],
    'medicine_intake_method' => [1 => 'Oral (taken by mouth)', 2 => 'Topical (applied to the skin)', 3 => 'Injectable (administered through injection)',4=>'Other'],
    'medicine_intake_supervised_by' => [1 => 'Admin', 2 => 'By Known', 3 => 'By Staff', 4 => 'other'],
    'medicine_frequency' => [1 => 'Daily', 5 => 'Bi-Daily', 2 => 'Weekly', 3 => 'Bi-weekly', 4 => 'Monthly'],
    'schdule_frequency' => [ 5 => 'Once',1 => 'Daily', 2 => 'Weekly', 3 => 'Bi-weekly', 4 => 'Monthly'],
    'work_shifts' => [1 => 'Morning', 2 => 'Afternoon', 3 => 'Evening', 4 => 'Night', 5 => 'Live In'],
    'patient_document_type' => [1 => 'Medical', 2 => 'Others'],
    'expense_type' => [1 => 'General', 2 => 'Specific'],
    'course_status' => [1 => 'Pending', 2 => 'In-progress', 3 => 'Completed', 4 => 'Incomplete'],
    'coupon_duration' => ['once' => 'Once', 'repeating' => 'Repeating', 'forever' => 'Forever'],
	'shift_schedule' => [
		'morning' => [	1 => ['Current Location', 'radio', 'onsite.png'], 
						2 => ['Waking Up', 'time', 'time.png'], 
						3 => ['Personal Hygiene', 'text', 'info.png'],
						4 => ['Breakfast/Food', 'time', 'food.png'],
						5 => ['Medication', 'time', 'medicine.png'], 
						6 => ['Activity', 'text', 'activity.png'], 
						7 => ['Appointments', 'time', 'apointment.png'], 
						8 => ['Incident', 'time', 'incident.png'],
						9 => ['Additional AM Comments', 'text', 'info.png'],
					  ],
		'afternoon' => [ 1 => ['Current Location', 'radio', 'onsite.png'], 
						 2 => ['Lunch/Food', 'time', 'food.png'], 
						 3 => ['Medication', 'time', 'medicine.png'],
						 4 => ['Activity', 'text', 'activity.png'],
						 5 => ['Appointments', 'time', 'apointment.png'],  
						 6 => ['Incident', 'time', 'incident.png'],
						 7 => ['Additional AM Comments', 'text', 'info.png'],
					  ],
		'night' => [ 1 => ['Current Location', 'radio', 'onsite.png'],
					 2 => ['Dinner/Food', 'time', 'food.png'],
					 3 => ['Supper/Food', 'time', 'food.png'],
					 4 => ['Medication', 'time', 'medicine.png'],
					 5 => ['Activity', 'text', 'activity.png'],
					 6 => ['Appointments', 'time', 'apointment.png'],  
					 7 => ['Incident', 'time', 'incident.png'],
					 8 => ['Additional AM Comments', 'text', 'info.png'],
				  ],			  
	],
	'subscription_benefits' => [
		'basic'     => ['allow_add_patients' => 'yes', 'allow_patient_logs' => 'yes', 'allow_add_images' => 'yes', 'allow_geofencing' => 'yes', 'allow_cashflow' => 'no'],
		'essential' => ['allow_add_patients' => 'yes', 'allow_patient_logs' => 'yes', 'allow_add_images' => 'yes', 'allow_geofencing' => 'no', 'allow_cashflow' => 'no'],
		'premium'   => ['allow_add_patients' => 'yes', 'allow_patient_logs' => 'yes', 'allow_add_images' => 'yes', 'allow_geofencing' => 'yes', 'allow_cashflow' => 'yes'],		  
	],
	//'content_pages' => [1 => 'About Us', 2 => 'Privacy Policy', 3 => 'Terms & Conditions']
	'content_pages' => [1 => 'About Us', 2 => 'Privacy Policy', 3 => 'Terms & Conditions', 4 => 'Home Page', 5 => 'Contact Us', 6 => 'Pricing Model',7=>'App Update Content'],
	'activity_recurrence' => [1 => 'Daily', 2 => 'Weekly', 3 => 'Monthly'],
	'task_type' => [0 => 'One Time', 1 => 'Continuous'],
	'task_status' => [0 => 'Incomplete', 1 => 'Complete', 2 => 'In-progress'],
	'activity_type' => [1 => 'All', 2 => 'Specific'], //Activity specify to all or specific client
	'week_days'=>['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'],
];
